# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
